name          'puppet-vault'
version       '0.0.1'
source        'puppet-vault'
author        'Costya Regev'
summary       'Install and manage Vault by HashiCorp '
description   ''
project_page  'puppet-vault'

dependency 'puppetlabs/stdlib', '>= 4.2.0 <5.0.0'
dependecny 'nanliu/archive', '>= 0.3.0'